# Generated by Django 4.1 on 2022-08-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="email", new_name="uemail",),
    ]
